name: myenv
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - spacy
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
